name: ligtaslink_mobile
description: LigtasLink safety audit prototype
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.0
  crypto: ^3.0.3
  cryptography: ^2.9.0
flutter:
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
